/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    Components: (typeof import("./src/components/index.vue"))["default"];
    ElAside: (typeof import("element-plus/es"))["ElAside"];
    ElAvatar: (typeof import("element-plus/es"))["ElAvatar"];
    ElBreadcrumb: (typeof import("element-plus/es"))["ElBreadcrumb"];
    ElBreadcrumbItem: (typeof import("element-plus/es"))["ElBreadcrumbItem"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCard: (typeof import("element-plus/es"))["ElCard"];
    ElContainer: (typeof import("element-plus/es"))["ElContainer"];
    ElHeader: (typeof import("element-plus/es"))["ElHeader"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElMain: (typeof import("element-plus/es"))["ElMain"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElMenuItemGroup: (typeof import("element-plus/es"))["ElMenuItemGroup"];
    ElPopover: (typeof import("element-plus/es"))["ElPopover"];
    ElSubItem: (typeof import("element-plus/es"))["ElSubItem"];
    ElSubmenu: (typeof import("element-plus/es"))["ElSubmenu"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    ElTag: (typeof import("element-plus/es"))["ElTag"];
    ElTooltip: (typeof import("element-plus/es"))["ElTooltip"];
    ElUpload: (typeof import("element-plus/es"))["ElUpload"];
    ElWatermark: (typeof import("element-plus/es"))["ElWatermark"];
    Header: (typeof import("./src/components/Header/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SideBar: (typeof import("./src/components/SideBar/index.vue"))["default"];
  }
}
