/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    Breadcrumb: (typeof import("./src/components/header/components/Breadcrumb.vue"))["default"];
    Collapse: (typeof import("./src/components/header/components/Collapse.vue"))["default"];
    Components: (typeof import("./src/components/index.vue"))["default"];
    ElAside: (typeof import("element-plus/es"))["ElAside"];
    ElAvatar: (typeof import("element-plus/es"))["ElAvatar"];
    ElBreadcrumb: (typeof import("element-plus/es"))["ElBreadcrumb"];
    ElBreadcrumbItem: (typeof import("element-plus/es"))["ElBreadcrumbItem"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCard: (typeof import("element-plus/es"))["ElCard"];
    ElCheckbox: (typeof import("element-plus/es"))["ElCheckbox"];
    ElCheckboxGroup: (typeof import("element-plus/es"))["ElCheckboxGroup"];
    ElCol: (typeof import("element-plus/es"))["ElCol"];
    ElColorPicker: (typeof import("element-plus/es"))["ElColorPicker"];
    ElContainer: (typeof import("element-plus/es"))["ElContainer"];
    ElDatePicker: (typeof import("element-plus/es"))["ElDatePicker"];
    ElDivider: (typeof import("element-plus/es"))["ElDivider"];
    ElDrawer: (typeof import("element-plus/es"))["ElDrawer"];
    ElDropdown: (typeof import("element-plus/es"))["ElDropdown"];
    ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"];
    ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"];
    ElFooter: (typeof import("element-plus/es"))["ElFooter"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElHeader: (typeof import("element-plus/es"))["ElHeader"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElImage: (typeof import("element-plus/es"))["ElImage"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElInputNumber: (typeof import("element-plus/es"))["ElInputNumber"];
    ElMain: (typeof import("element-plus/es"))["ElMain"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElOption: (typeof import("element-plus/es"))["ElOption"];
    ElPopover: (typeof import("element-plus/es"))["ElPopover"];
    ElRadio: (typeof import("element-plus/es"))["ElRadio"];
    ElRadioGroup: (typeof import("element-plus/es"))["ElRadioGroup"];
    ElRate: (typeof import("element-plus/es"))["ElRate"];
    ElRow: (typeof import("element-plus/es"))["ElRow"];
    ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"];
    ElSelect: (typeof import("element-plus/es"))["ElSelect"];
    ElStep: (typeof import("element-plus/es"))["ElStep"];
    ElSteps: (typeof import("element-plus/es"))["ElSteps"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
    ElTable: (typeof import("element-plus/es"))["ElTable"];
    ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"];
    ElTabPane: (typeof import("element-plus/es"))["ElTabPane"];
    ElTabs: (typeof import("element-plus/es"))["ElTabs"];
    ElTag: (typeof import("element-plus/es"))["ElTag"];
    ElTimePicker: (typeof import("element-plus/es"))["ElTimePicker"];
    ElTooltip: (typeof import("element-plus/es"))["ElTooltip"];
    ElTour: (typeof import("element-plus/es"))["ElTour"];
    ElTourStep: (typeof import("element-plus/es"))["ElTourStep"];
    ElWatermark: (typeof import("element-plus/es"))["ElWatermark"];
    Footer: (typeof import("./src/components/footer/index.vue"))["default"];
    FullScreen: (typeof import("./src/components/header/components/FullScreen.vue"))["default"];
    Header: (typeof import("./src/components/header/index.vue"))["default"];
    Message: (typeof import("./src/components/header/components/Message.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Setting: (typeof import("./src/components/header/components/Setting.vue"))["default"];
    Sidebar: (typeof import("./src/components/sidebar/index.vue"))["default"];
    SwitchLanguage: (typeof import("./src/components/header/components/SwitchLanguage.vue"))["default"];
    Tour: (typeof import("./src/components/header/components/Tour.vue"))["default"];
    User: (typeof import("./src/components/header/components/User.vue"))["default"];
  }
}
